config/routes.rb
Rails.application.routes.draw do
  
  resources :forms
  resources :tipo_answers
  #routes for Answers
  resources :answers
  #routes for Questions
  resources :questions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tipo_answer.rb
class TipoAnswer < ActiveRecord::Base
	validates :topic, :presence => true

	def initialize
		
	end

	def rango5 (cad)
		if cad === 'Rango 5'
			range_5 = [1,2,3,4,5]
		end
		return range_5
	end

end

app/controllers/tipo_answers_controller.rb
class TipoAnswersController < ApplicationController
  before_action :set_tipo_answer, only: [:show, :edit, :update, :destroy]

  # GET /tipo_answers
  # GET /tipo_answers.json
  def index
    @tipo_answers = TipoAnswer.all
  end

  # GET /tipo_answers/1
  # GET /tipo_answers/1.json
  def show
  end

  # GET /tipo_answers/new
  def new
    @tipo_answer = TipoAnswer.new
  end

  # GET /tipo_answers/1/edit
  def edit
  end

  # POST /tipo_answers
  # POST /tipo_answers.json
  def create
    @tipo_answer = TipoAnswer.new(tipo_answer_params)

    respond_to do |format|
      if @tipo_answer.save
        format.html { redirect_to @tipo_answer, notice: 'Tipo answer was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_answer }
      else
        format.html { render :new }
        format.json { render json: @tipo_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_answers/1
  # PATCH/PUT /tipo_answers/1.json
  def update
    respond_to do |format|
      if @tipo_answer.update(tipo_answer_params)
        format.html { redirect_to @tipo_answer, notice: 'Tipo answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_answer }
      else
        format.html { render :edit }
        format.json { render json: @tipo_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_answers/1
  # DELETE /tipo_answers/1.json
  def destroy
    @tipo_answer.destroy
    respond_to do |format|
      format.html { redirect_to tipo_answers_url, notice: 'Tipo answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_answer
      @tipo_answer = TipoAnswer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_answer_params
      params.require(:tipo_answer).permit(:topic)
    end
end

app/helpers/tipo_answers_helper.rb
module TipoAnswersHelper
end

app/views/tipo_answers/_form.html.erb
<%= form_for(tipo_answer) do |f| %>
  <% if tipo_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_answer.errors.count, "error") %> prohibited this tipo_answer from being saved:</h2>

      <ul>
      <% tipo_answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %>
    <%= f.text_field :topic %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_answers/edit.html.erb
<h1>Editing Tipo Answer</h1>

<%= render 'form', tipo_answer: @tipo_answer %>

<%= link_to 'Show', @tipo_answer %> |
<%= link_to 'Back', tipo_answers_path %>

app/views/tipo_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Answers</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_answers.each do |tipo_answer| %>
      <tr>
        <td><%= tipo_answer.topic %></td>
        <td><%= link_to 'Show', tipo_answer %></td>
        <td><%= link_to 'Edit', edit_tipo_answer_path(tipo_answer) %></td>
        <td><%= link_to 'Destroy', tipo_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Answer', new_tipo_answer_path %>

app/views/tipo_answers/new.html.erb
<h1>New Tipo Answer</h1>

<%= render 'form', tipo_answer: @tipo_answer %>

<%= link_to 'Back', tipo_answers_path %>

app/views/tipo_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @tipo_answer.topic %>
</p>

<%= link_to 'Edit', edit_tipo_answer_path(@tipo_answer) %> |
<%= link_to 'Back', tipo_answers_path %>