config/routes.rb
Rails.application.routes.draw do
  
  resources :forms
  resources :tipo_answers
  #routes for Answers
  resources :answers
  #routes for Questions
  resources :questions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	validates :value, :presence => true
	belongs_to :question

	def self.to_csv
    attributes = %w{form_id question_id created_at value}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |answer|
        csv << attributes.map{ |attr| answer.send(attr) }
      end
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  require 'csv'
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html
      format.csv { send_data @answers.to_csv, filename: "answers-#{Date.today}.csv" }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        return 'listo'
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    @answer = Answer.find(params[:id])
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:value, :question_id, :form_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(answer) do |f| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Formulario_No %>
    <%= f.text_field :form_id %>
  </div>

  <div class="field">
    <%= f.label :Pregunta_No %>
    <%= f.number_field :question_id %>
  </div>

  <div class="field">
    <%= f.label :Valor_Respuesta %>
    <%= f.text_field :value %>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar Respuesta', class: "btn btn-success" %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<!-- ================================================================================ -->
<!-- Test Analisistem -->
<!-- Project: LUTO FORM -->
<!-- Author: Johnny Zapata Serna -->
<!-- Description: program to evaluate quality of Luto Clinic implementing a form-->
<!-- ================================================================================ -->

<div class="container">
  <h1>Respuestas</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Consecutive </th>
        <th>| Code Question </th>
        <th>| date </th>
        <th>| value</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.form_id %></td>
          <td><%= answer.question_id %></td>
          <td><%= answer.created_at %></td>
          <td><%= answer.value %></td>
          <td><%= link_to 'Show', answer %></td>
          <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
          <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <p><%= link_to("Generar Archivo CSV", answers_path(format: :csv), class: "btn btn-success",) %></p>


</div>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<div class="container">
	<h4>Detalles de la Respuesta</h4>
</div>

<p>
  <strong>Formulario Número: </strong>
  <%= @answer.form_id %>
</p>

<p>
  <strong>Código de la Pregunta: </strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Fecha de Respuesta: </strong>
  <%= @answer.created_at %>
</p>

<p>
  <strong>Valor de la Respuesta: </strong>
  <%= @answer.value %>
</p>

<%= link_to 'Back', answers_path %>