config/routes.rb
Rails.application.routes.draw do
  
  resources :forms
  resources :tipo_answers
  #routes for Answers
  resources :answers
  #routes for Questions
  resources :questions

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/forms_controller.rb
class FormsController < AnswersController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
    @answer = Answer.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:observation)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_for(form) do |f| %>
  <% if form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions" align="center">
    <%= f.submit 'IR A LA ENCUESTA', class: "btn btn-success" %>
  </div>

  <div class="field" align="center">
    <%= f.label :acepto %>
    <%= f.check_box :observation %>
  </div>

<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<!-- ================================================================================ -->
<!-- Test Analisistem -->
<!-- Project: LUTO FORM -->
<!-- Author: Johnny Zapata Serna -->
<!-- Description: program to evaluate quality of Luto Clinic implementing a form-->
<!-- ================================================================================ -->

<div class="container">
  <h1>Formularios Abiertos</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Observation</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @forms.each do |form| %>
        <tr>
          <td><%= form.observation %></td>
          <td><%= link_to 'Show', form %></td>
          <td><%= link_to 'Edit', edit_form_path(form) %></td>
          <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h2 align="center" style="color: red">Encuesta de Satisfacción</h2>

<%= render 'form', form: @form %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<!-- Form -->
<div class="container">
  </br>
  <div class="container" align="center">
  	<h2 style="color: red">Encuesta de Satisfacción</h2>
	</br>
	<h4>Responde a cada pregunta según la opción correspondiente</h4>
  </div>
  <div class="row">
  	</br>
    
    <!-- Show questions by consecutive and register each answer -->
    	
    <% Question.all.map do |q|%>

		<div class="container border-top" >
			</br>
			<div class="row">
				<h5 > Pregunta <%= q.id %>: </h5>
			</div>
			<div class="row">
				<h6><%= q.description %></h6>
			</div>
			
			<!-- ====== Save Answers ====== -->
			<% answer = Answer.new %>
		    <%= form_for(answer) do |f| %>
			  <% if answer.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

			      <ul>
			      <% answer.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>

			 	<div class="field">
				    <!-- condition to save answers with type answer Rango 5 -->
				    <% if q.type_answer === 'Rango 5' %>
						<% f.label :Formulario_No %>
						<% u = request.fullpath.split('/') %>
						<% consecutive = u.last.to_s  %>
						<%= f.hidden_field :form_id, :value => consecutive, :readonly=>true %>

						<div class="field">
						    <% f.label :Pregunta_No %>
						    <% code_q = q.id  %>
						    <%= f.hidden_field :question_id, :value=>code_q, :readonly=>true %>
						</div>

						<div class="row">
						<div class="field">
						    <%= f.select :value, options_for_select(["seleccionar","1","2","3","4","5"]) %>
						</div>

						<div class="actions">
							<%= f.submit 'Guardar Respuesta', class: "btn btn-success" %>
						</div>
						</div>
					<% end %>

					<!-- condition to save answers with type answer Number -->
					<% if q.type_answer === 'Numero Entero' %>
						<% f.label :Formulario_No %>
						<% u = request.fullpath.split('/') %>
						<% consecutive = u.last.to_s  %>
						<%= f.hidden_field :form_id, :value => consecutive, :readonly=>true %>

						<div class="field">
						    <% f.label :Pregunta_No %>
						    <% code_q = q.id  %>
						    <%= f.hidden_field :question_id, :value=>code_q, :readonly=>true %>
						</div>

						<div class="row">
						<div class="field">
						    <%= f.number_field :value %>
						</div>

						<div class="actions">
							<%= f.submit 'Guardar Respuesta', class: "btn btn-success" %>
						</div>
						</div>
					<% end %>

					<!-- condition to save answers with type answer Boolean -->
					<% if q.type_answer === 'Si o No' %>
						<% f.label :Formulario_No %>
						<% u = request.fullpath.split('/') %>
						<% consecutive = u.last.to_s  %>
						<%= f.hidden_field :form_id, :value => consecutive, :readonly=>true %>

						<div class="field">
						    <% f.label :Pregunta_No %>
						    <% code_q = q.id  %>
						    <%= f.hidden_field :question_id, :value=>code_q, :readonly=>true %>
						</div>

						<div class="row">
						<div class="field">
						    <%= f.select :value, options_for_select(["seleccionar","Si","No"]) %>
						</div>

						<div class="actions">
							<%= f.submit 'Guardar Respuesta', class: "btn btn-success" %>
						</div>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
    <% end -%>
    </br>

    <div class="container text-center">
    	<div class="thumbnail" style="border-style: solid;">
    		<h4><%= link_to 'Terminar', '/' %></h4>
    	</div>
    </div>


  </div>
</div>